// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"EffiPlat/backend/internal/handler"
	"EffiPlat/backend/internal/repository"
	"EffiPlat/backend/internal/service"
	"github.com/google/wire"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeUserHandler is the injector for UserHandler and its dependencies.
// It takes the database connection as input.
// This function will be callable from other packages (like main) because it's exported.
func InitializeUserHandler(db *gorm.DB, logger *zap.Logger) (*handler.UserHandler, error) {
	userRepository := repository.NewUserRepository(db, logger)
	roleRepositoryImpl := repository.NewRoleRepository(db, logger)
	userService := service.NewUserService(userRepository, roleRepositoryImpl, logger)
	userHandler := handler.NewUserHandler(userService)
	return userHandler, nil
}

// InitializeRoleHandler is the injector for RoleHandler and its dependencies.
func InitializeRoleHandler(db *gorm.DB, logger *zap.Logger) (*handler.RoleHandler, error) {
	roleRepositoryImpl := repository.NewRoleRepository(db, logger)
	roleServiceImpl := service.NewRoleService(roleRepositoryImpl, logger)
	roleHandler := handler.NewRoleHandler(roleServiceImpl, logger)
	return roleHandler, nil
}

// InitializeAuthHandler is the injector for AuthHandler.
// Make sure it has the //go:build wireinject tags if it's in a wireinject file.
// If wire.go is itself a wireinject file (based on build tags at the top),
// then this function template is fine.
func InitializeAuthHandler(db *gorm.DB, jwtKey []byte, logger *zap.Logger) (*handler.AuthHandler, error) {
	userRepository := repository.NewUserRepository(db, logger)
	authService := service.NewAuthService(userRepository, jwtKey, logger)
	authHandler := handler.NewAuthHandler(authService)
	return authHandler, nil
}

// InitializePermissionHandler is the injector for PermissionHandler and its dependencies.
func InitializePermissionHandler(db *gorm.DB, logger *zap.Logger) (*handler.PermissionHandler, error) {
	permissionRepositoryImpl := repository.NewPermissionRepository(db, logger)
	roleRepositoryImpl := repository.NewRoleRepository(db, logger)
	permissionService := service.NewPermissionService(permissionRepositoryImpl, roleRepositoryImpl, logger)
	permissionHandler := handler.NewPermissionHandler(permissionService, logger)
	return permissionHandler, nil
}

// InitializeResponsibilityHandler is the injector for ResponsibilityHandler and its dependencies.
func InitializeResponsibilityHandler(db *gorm.DB, logger *zap.Logger) (*handler.ResponsibilityHandler, error) {
	responsibilityRepository := repository.NewGormResponsibilityRepository(db, logger)
	responsibilityService := service.NewResponsibilityService(responsibilityRepository, logger)
	responsibilityHandler := handler.NewResponsibilityHandler(responsibilityService, logger)
	return responsibilityHandler, nil
}

// InitializeResponsibilityGroupHandler is the injector for ResponsibilityGroupHandler and its dependencies.
func InitializeResponsibilityGroupHandler(db *gorm.DB, logger *zap.Logger) (*handler.ResponsibilityGroupHandler, error) {
	responsibilityGroupRepository := repository.NewGormResponsibilityGroupRepository(db, logger)
	responsibilityRepository := repository.NewGormResponsibilityRepository(db, logger)
	responsibilityGroupService := service.NewResponsibilityGroupService(responsibilityGroupRepository, responsibilityRepository, logger)
	responsibilityGroupHandler := handler.NewResponsibilityGroupHandler(responsibilityGroupService, logger)
	return responsibilityGroupHandler, nil
}

// InitializeServiceInstanceHandler is the injector for ServiceInstanceHandler.
func InitializeServiceInstanceHandler(db *gorm.DB, logger *zap.Logger, serviceRepo repository.ServiceRepository, envRepo repository.EnvironmentRepository) (*handler.ServiceInstanceHandler, error) {
	serviceInstanceRepository := repository.NewServiceInstanceRepository(db, logger)
	serviceInstanceService := service.NewServiceInstanceService(serviceInstanceRepository, serviceRepo, envRepo, logger)
	serviceInstanceHandler := handler.NewServiceInstanceHandler(serviceInstanceService, logger)
	return serviceInstanceHandler, nil
}

// wire.go:

// ProviderSet for user components
var UserSet = wire.NewSet(repository.NewUserRepository, repository.NewRoleRepository, service.NewUserService, handler.NewUserHandler, wire.Bind(new(repository.RoleRepository), new(*repository.RoleRepositoryImpl)))

// ProviderSet for role components
var RoleSet = wire.NewSet(repository.NewRoleRepository, service.NewRoleService, handler.NewRoleHandler, wire.Bind(new(repository.RoleRepository), new(*repository.RoleRepositoryImpl)), wire.Bind(new(service.RoleService), new(*service.RoleServiceImpl)))

// ProviderSet for auth components
var AuthSet = wire.NewSet(repository.NewUserRepository, service.NewAuthService, handler.NewAuthHandler)

// ProviderSet for permission components
var PermissionSet = wire.NewSet(repository.NewPermissionRepository, wire.Bind(new(repository.PermissionRepository), new(*repository.PermissionRepositoryImpl)), repository.NewRoleRepository, wire.Bind(new(repository.RoleRepository), new(*repository.RoleRepositoryImpl)), service.NewPermissionService, handler.NewPermissionHandler)

// ProviderSet for responsibility components
var ResponsibilitySet = wire.NewSet(repository.NewGormResponsibilityRepository, service.NewResponsibilityService, handler.NewResponsibilityHandler)

// ProviderSet for responsibility group components
var ResponsibilityGroupSet = wire.NewSet(repository.NewGormResponsibilityGroupRepository, repository.NewGormResponsibilityRepository, service.NewResponsibilityGroupService, handler.NewResponsibilityGroupHandler)

// ProviderSet for service instance components
var ServiceInstanceSet = wire.NewSet(repository.NewServiceInstanceRepository, service.NewServiceInstanceService, handler.NewServiceInstanceHandler)
